manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: GabriWar
      url-base: https://github.com/GabriWar
      # Additional modules containing boards/shields/custom code can be listed here as well.
      # See:
      # - https://zmk.dev/docs/features/modules
      # - https://docs.zephyrproject.org/3.5.0/develop/west/manifest.html#projects
    - name: m165437 #NICE VIEW GEM THINGY
      url-base: https://github.com/M165437 
  projects:
    - name: eyelash_corne
      url: https://github.com/GabriWar/zmk-new_corne
      revision: main
    - name: zmk
      remote: GabriWar
      revision: main
      import: app/west.yml
    - name: nice-view-gem 
      remote: m165437 
      revision: main 
  self:
    path: config
